[project]
name = "yolov5-deepsort-driverdistracted-driving-behavior-detection"
version = "0.1.0"
description = "Deep Learning-Based Driver Distraction (Fatigue + Risk Behavior) Early Warning System Utilizing YOLOv5 + Deepsort for Monitoring and Alerting Driver Risky Driving Behaviors"
readme = "README.md"
authors = [
    { name = "LukasWestholt", email = "support@lukaswestholt.de" }
]
requires-python = "==3.10.*"
dependencies = [
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "numpy<2",
    "opencv-python>=4.11.0.86",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
    "pyyaml>=6.0.3",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "scipy>=1.15.3",
    "imutils>=0.5.4",
    "dlib",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]
dlib = [
    { url = "https://github.com/z-mahmud22/Dlib_Windows_Python3.x/raw/2cc3bb593701cc7fc4007a299c3f19b34a76c002/dlib-19.22.99-cp310-cp310-win_amd64.whl", marker = "platform_system == 'Windows'" },
    { url = "https://github.com/LukasWestholt/dlib-compiled/releases/download/v1.0.1/dlib-20.0.99-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl", marker = "platform_system != 'Windows'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.build-backend]
module-name = ["yolov5_deepsort_driverdistracted_driving_behavior_detection", "models"]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
